/* AUTO-GENERATED by tools/gen_lexicon.py — AI-drafted 词义扩展 (未审校).
   Authored js/lexicon.js wins over these. Run the tool to populate; promote
   good entries into lexicon.js to drop the "AI 草拟" label. Empty until generated. */
window.LEXICON_GEN = {};
