#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_lexicon.py — draft 词义扩展 (lexicon) entries for every vocab word that is
NOT already hand-authored in js/lexicon.js. Mirrors gen_audio.py's "local batch,
commit the output" pattern. BYOK: set ANTHROPIC_API_KEY in your env (never commit it).

  ANTHROPIC_API_KEY=sk-ant-... python3 tools/gen_lexicon.py            # draft all missing
  python3 tools/gen_lexicon.py --day 2          # only Day 2's vocab
  python3 tools/gen_lexicon.py --limit 20       # cap calls (cost control)
  python3 tools/gen_lexicon.py --model claude-haiku-4-5   # cheaper model

Output → js/lexicon-gen.js  (window.LEXICON_GEN, entries marked ai:true). Idempotent:
skips words already in lexicon.js (authored) or lexicon-gen.js (already drafted).
The app uses authored LEXICON first, then LEXICON_GEN (labelled "AI 草拟"), then the
runtime AI fallback. Promote good drafts into lexicon.js to drop the label.

This standardizes enrichment for ALL paragraphs — current and future. Re-run after
adding any new day. See docs/CONTENT-STANDARD.md.
"""
import os, re, sys, json, time, argparse, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LESSONS = os.path.join(ROOT, "js", "lessons.js")
LEX     = os.path.join(ROOT, "js", "lexicon.js")
OUT     = os.path.join(ROOT, "js", "lexicon-gen.js")
API_URL = "https://api.anthropic.com/v1/messages"

def parse_vocab(src):
    """Tolerant parse of lessons.js → [{w,r,pos,day}], reading the vocab `w`/`r`/`pos`."""
    out, day = [], 0
    for m in re.finditer(r'(?:day\s*:\s*(\d+))|(?:\bw:"([^"]+)"\s*,\s*r:"([^"]+)")', src):
        if m.group(1):
            day = int(m.group(1)); continue
        w, r = m.group(2), m.group(3)
        tail = src[m.end(): m.end()+400]
        pm = re.search(r'\bpos:"([^"]*)"', tail)
        pos = pm.group(1) if pm else ""
        out.append({"w": w, "r": r, "pos": pos, "day": day})
    # de-dupe by word, keep first
    seen, uniq = set(), []
    for v in out:
        if v["w"] in seen: continue
        seen.add(v["w"]); uniq.append(v)
    return uniq

def existing_keys(path):
    if not os.path.exists(path): return set()
    s = open(path, encoding="utf-8").read()
    return set(re.findall(r'"([^"]+)"\s*:\s*\{', s))

SYS = ("你是日语词汇编纂者，服务于中文母语的 N2 学习者。为给定的词输出一个 JSON 对象（只输出 JSON，"
       "不要解释、不要代码块）。字段：①若为复合动词，加 compound:{roots:[{w,m}],why,pattern,family:[{w,m}]}；"
       "②近义/反义/相近表达 syn/ant/related，元素为 {w,m,note}；③note：用法区别（什么场合用哪个）。"
       "所有日语都用「漢字[かな]」加振假名。m/note/why 用中文，简洁。不适用的字段可省略。")

def draft(word, reading, pos, model, key):
    body = json.dumps({
        "model": model, "max_tokens": 700,
        "system": SYS,
        "messages": [{"role": "user", "content": f"词：{word}（{reading}）　词性：{pos}"}],
    }).encode("utf-8")
    req = urllib.request.Request(API_URL, data=body, headers={
        "content-type": "application/json", "x-api-key": key,
        "anthropic-version": "2023-06-01",
    })
    with urllib.request.urlopen(req, timeout=60) as resp:
        j = json.load(resp)
    txt = (j.get("content") or [{}])[0].get("text", "")
    mm = re.search(r'\{[\s\S]*\}', txt)
    if not mm: raise ValueError("no JSON in response")
    obj = json.loads(mm.group(0)); obj["ai"] = True
    return obj

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--day", type=int, default=0)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--model", default="claude-haiku-4-5")
    args = ap.parse_args()

    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key: sys.exit("✗ set ANTHROPIC_API_KEY in your env (never commit it).")

    vocab = parse_vocab(open(LESSONS, encoding="utf-8").read())
    have = existing_keys(LEX) | existing_keys(OUT)
    todo = [v for v in vocab if v["w"] not in have and (not args.day or v["day"] == args.day)]
    if args.limit: todo = todo[:args.limit]
    print(f"vocab={len(vocab)}  already covered={len(have)}  to draft={len(todo)}")

    gen = {}
    if os.path.exists(OUT):
        s = open(OUT, encoding="utf-8").read()
        m = re.search(r'\{[\s\S]*\}', s)
        if m:
            try: gen = json.loads(m.group(0))
            except Exception: gen = {}

    made = 0
    for v in todo:
        try:
            gen[v["w"]] = draft(v["w"], v["r"], v["pos"], args.model, key); made += 1
            print(f"  ✓ {v['w']} ({v['r']})")
        except Exception as e:
            print(f"  ✗ {v['w']}: {e}")
        time.sleep(0.5)  # gentle rate limit
        # checkpoint每隔10个写盘，断了也不丢
        if made and made % 10 == 0: write(gen)
    write(gen)
    print(f"\nDone. drafted={made}  total in lexicon-gen.js={len(gen)}  → {OUT}")
    print("Review js/lexicon-gen.js; promote good entries into js/lexicon.js to drop the 'AI 草拟' label.")

def write(gen):
    header = ("/* AUTO-GENERATED by tools/gen_lexicon.py — AI-drafted 词义扩展 (未审校).\n"
              "   Authored js/lexicon.js wins over these. Promote good entries there. */\n")
    open(OUT, "w", encoding="utf-8").write(header + "window.LEXICON_GEN = " +
        json.dumps(gen, ensure_ascii=False, indent=1) + ";\n")

if __name__ == "__main__":
    main()
